mqtt:
  host-url: tcp://test.mosquitto.org:1883
  clientID: esp32-server
  default-topic: 7C:9E:BD:47:2C:14-telemetry
  timeout: 100
  keepalive: 100


spring:
  h2:
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
